# Tutorial 4: Introduction to Tensorflow

TensorFlow is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered applications.

**1. Import library**

In [1]:
import tensorflow as tf
import numpy as np

**2. Tensorflow array with one at all places**

In [2]:
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()
b=tf.ones((2,2,2))
#with sess.as_default():
print(b)
b.eval(session=sess)

Tensor("ones:0", shape=(2, 2, 2), dtype=float32)


array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

**3. Tensorflow array with particular value at all places**

In [3]:
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()
c=tf.fill((2,2), value=.8)
c.eval(session=sess)

array([[0.8, 0.8],
       [0.8, 0.8]], dtype=float32)

**4. Tensorflow constant**

In [4]:
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()
d= tf.constant(3)
d.eval(session=sess)

3

**5. Tensorflow array with random normal values**

In [5]:
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()
e= tf.random.normal((2, 2), mean=0, stddev=1)
e.eval(session=sess)

array([[ 0.11224773,  1.2237849 ],
       [ 1.0530356 , -0.61695355]], dtype=float32)

**6. Tensorflow array with random values with in fixed range**

In [6]:
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()
f= tf.random.uniform((2, 2), minval=-2, maxval=2)
f.eval(session=sess)

array([[-1.8963976 ,  1.5516152 ],
       [-1.9191875 , -0.03428411]], dtype=float32)

**7. Tensorflow adding two arrays**

In [7]:
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()
g=tf.ones((2,2)) 
h= tf.ones((2,2)) 
i=g+h
i.eval(session=sess)

array([[2., 2.],
       [2., 2.]], dtype=float32)

**8. Tensorflow multiply fixed value**

In [8]:
j = 2 * i 
j.eval(session=sess) 

array([[4., 4.],
       [4., 4.]], dtype=float32)

**9. Tensorflow array multiplication**

In [9]:
k= tf.fill((2,2), 2.) 
l = tf.fill((2,2), 7.) 
m = k *l 
m.eval(session=sess) 

array([[14., 14.],
       [14., 14.]], dtype=float32)

**10. Tensorflow Identity matrix**

In [10]:
n = tf.eye(4) 
n.eval(session=sess) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

**11. Tensorflow diagonal matrix**

In [11]:
p = tf.linalg.diag(n) 
p.eval(session=sess) 

array([[[1., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 1.]]], dtype=float32)

**12. Tensorflow matrix**

In [12]:
q = tf.ones((2, 3))
q.eval(session=sess) 

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

**13. Tensorflow matrix transpose**

In [13]:
r = tf.transpose(q)
r.eval(session=sess) 

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

**14. Tensorflow matrix multiplication**

In [14]:
a = tf.ones((2, 3)) 
a.eval(session=sess)

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [15]:
b = tf.ones((3, 4))
b.eval(session=sess) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [16]:
c = tf.matmul(a, b) 
c.eval(session=sess)

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)

**15. Tensorflow Array reshape**

In [17]:
d = tf.reshape(c, (2, 2, 2)) 
d.eval(session=sess) 

array([[[3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.]]], dtype=float32)

In [18]:
c.get_shape()

TensorShape([2, 4])

**16. Tensorflow array broadcasting**

In [19]:
a = tf.ones((2, 2)) 
a.eval(session=sess) 

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [20]:
b = tf.range(0, 2, 1, dtype=tf.float32) 
b.eval(session=sess) 

array([0., 1.], dtype=float32)

In [21]:
c = a + b 
c.eval(session=sess) 

array([[1., 2.],
       [1., 2.]], dtype=float32)

**17. Tensorflow session**

In [22]:
# session
sess = tf.compat.v1.Session() 
a = tf.ones((3, 3)) 
b = tf.matmul(a, a) 
b.eval(session=sess) 

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [23]:
sess.run(b)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

Tutorial by E&ICT Academy, IIITDM Jabalpur ( Poornima Singh Thakur, Nishant Khare, Samir Jain and Aparajita Ojha)

**Reference :** - https://www.tensorflow.org/