In [1]:
# importing the library
import numpy as np


In [2]:
# creating the input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
print ('\n Input:')
print(X)


 Input:
[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]


In [3]:
# creating the output array
y=np.array([[1],[1],[0]])
print ('\n Actual Output:')
print(y)


 Actual Output:
[[1]
 [1]
 [0]]


In [4]:
# defining the Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [5]:
# derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

In [12]:
# initializing the variables
epoch=2 # number of training iterations
lr=0.2 # learning rate
inputlayer_neurons = X.shape[1] # number of features in data set
print(inputlayer_neurons)
hiddenlayer_neurons = 3 # number of hidden layers neurons
output_neurons = 1 # number of neurons at output layer


4


In [13]:
# initializing weight and bias
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
print("weight of hidden", wh)
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
print("weight of output", wout)
bout=np.random.uniform(size=(1,output_neurons))

weight of hidden [[0.71777533 0.25578766 0.23812537]
 [0.98197023 0.12223253 0.82742567]
 [0.9160162  0.75544201 0.06235073]
 [0.78083753 0.63544248 0.43422646]]
weight of output [[0.47794045]
 [0.69786351]
 [0.00632153]]


In [14]:
# training the model
for i in range(epoch):

    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    print(hiddenlayer_activations)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)
    print(output)
    
    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

print ('\n Output from the model:')
print (output)


[[0.86738528 0.84098171 0.6514305 ]
 [0.93455575 0.90895926 0.74260636]
 [0.88153544 0.80408057 0.83012439]]
[[0.74624629]
 [0.7611165 ]
 [0.74284954]]
[[0.86749225 0.84112549 0.6514413 ]
 [0.93454154 0.9088315  0.74261263]
 [0.88119946 0.80290269 0.83011859]]
[[0.7404883 ]
 [0.75516523]
 [0.7364737 ]]

 Output from the model:
[[0.7404883 ]
 [0.75516523]
 [0.7364737 ]]
