In [3]:
# importing the library
import numpy as np


In [4]:
# creating the input array
X=np.array([[1,0,1],[1,0,1],[0,1,0]])
print ('\n Input:')
print(X)


 Input:
[[1 0 1]
 [1 0 1]
 [0 1 0]]


In [5]:
# creating the output array
y=np.array([[1],[1],[0]])
print ('\n Actual Output:')
print(y)


 Actual Output:
[[1]
 [1]
 [0]]


In [6]:
# defining the Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [7]:
# derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

In [14]:
# initializing the variables
epoch=1000 # number of training iterations
lr=0.1 # learning rate
inputlayer_neurons = X.shape[1] # number of features in data set
output_neurons = 1 # number of neurons at output layer

In [15]:
# initializing weight and bias
wout=np.random.uniform(size=(inputlayer_neurons,output_neurons))
print("weight of output", wout)
bout=np.random.uniform(size=(1,output_neurons))

weight of output [[0.02858024]
 [0.42653381]
 [0.82094259]]


In [16]:
# training the model
for i in range(epoch):

    #Forward Propogation
    output_layer_input1=np.dot(X,wout)
    output_layer_input=output_layer_input1 + bout
    output = sigmoid(output_layer_input)
    #print(output)
    
    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    d_output = E * slope_output_layer
    #print(d_output)
    Error_at_input_layer = d_output.dot(wout.T)
    #print(Error_at_input_layer)
    wout += X.T.dot(d_output) *lr
    #print(wout)
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    

print ('\n Output from the model:')
print (output)



 Output from the model:
[[0.95683796]
 [0.95683796]
 [0.07260153]]
